// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzabbJEbvdj7AebB8KhZXM0jhDhB6uVxA',
    appId: '1:809057116961:web:9d3ac4ac8dadba4f56d460',
    messagingSenderId: '809057116961',
    projectId: 'finance-d4e12',
    authDomain: 'finance-d4e12.firebaseapp.com',
    storageBucket: 'finance-d4e12.appspot.com',
    measurementId: 'G-V8LYE53E9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebX7xujx5Z1o5Fu-DOTZLBWC4S-tjcAE',
    appId: '1:809057116961:android:a66be443518c55f656d460',
    messagingSenderId: '809057116961',
    projectId: 'finance-d4e12',
    storageBucket: 'finance-d4e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBghgHqqnya1aHXvhjC4HQdbNKHtUtQUbI',
    appId: '1:809057116961:ios:cb424e450965c02d56d460',
    messagingSenderId: '809057116961',
    projectId: 'finance-d4e12',
    storageBucket: 'finance-d4e12.appspot.com',
    iosClientId:
        '809057116961-bjqp1all22ilrol13qa4cl4fts266j26.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBghgHqqnya1aHXvhjC4HQdbNKHtUtQUbI',
    appId: '1:809057116961:ios:cb424e450965c02d56d460',
    messagingSenderId: '809057116961',
    projectId: 'finance-d4e12',
    storageBucket: 'finance-d4e12.appspot.com',
    iosClientId:
        '809057116961-bjqp1all22ilrol13qa4cl4fts266j26.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );
}
